export const config = {
  //serverUrl: 'https://server.scankar.com/api/v1/',
  //socketUrl: 'https://server.scankar.com',
  serverUrl: 'http://localhost:4000/api/v1/',
  socketUrl: 'http://localhost:4000',
  scanUrl: 'http://user.scankar.com/',
  appTitle: 'Scankar',
  appDesc: 'The ultimate restaurant management system with PMS & POS.',
  mode: 'development',
  version: '1.0.0',
  appLogo: 'assets/media/logos/Scankar_footer.png',
  deployer: 'Codeaxes',
  year: '2020',
  session_timeout: 12000000,
};
